### PR TITLE
Added support for headers

### PR DESCRIPTION
**Pull request by samuelbailey123**

### CODE REVIEW

**Comment by megapro17** [comment]
That's not a good solution, there is a lot libraries that can get random user agent

**Comment by samuelbailey123** [comment]
Why does it matter if it uses random agents or not?

**Comment by samuelbailey123** [comment]
I'll user a randomizer to pick a user-agent, I just don't understand why it matters. Maybe you could explain

**Comment by megapro17** [comment]
Because if everyone will download with the same user agent it will stop working eventually

**Comment by samuelbailey123** [comment]
@megapro17 Updated to use dynamic user-agents
@sj-dan Anything else you see needed?

**Pull request merged**
